name: "PR Workflow"

run-name: "PR Workflow - ${{ github.actor }}"

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GITHUB_ACTIONS: true

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display GITHUB_ACTIONS environment variable
        run: |
          echo "GITHUB_ACTIONS variable value: $GITHUB_ACTIONS"
      
      - name: Display branch and repository name
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.head_ref }}"
          echo "Base branch: ${{ github.base_ref }}"
      
      - name: Display triggering event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Triggered by: ${{ github.actor }}"
